## DATA PREPROCESSING AND DATA CLEANING

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('A.csv')
del df['DATETIME']
del df['F_PU9']
del df['S_PU9']
del df['F_PU5']
del df['S_PU5']
del df['F_PU3']
del df['S_PU3']
del df['S_PU1']
df.head()

,L_T1,L_T2,L_T3,L_T4,L_T5,L_T6,L_T7,F_PU1,F_PU2,S_PU2,...,P_J256,P_J289,P_J415,P_J302,P_J306,P_J307,P_J317,P_J14,P_J422,ATT_FLAG
0,2.44,5.24,3.19,4.10,2.86,5.50,4.39,93.63,93.65,1,...,70.00,28.22,85.87,21.69,82.72,21.58,71.99,39.33,29.64,0
1,2.66,4.53,3.20,4.18,3.29,5.44,4.53,89.41,89.43,1,...,87.73,24.45,84.87,29.81,86.62,29.81,59.76,42.17,26.15,0
2,3.11,3.66,3.66,4.21,3.87,5.15,3.22,89.88,89.89,1,...,89.29,23.90,87.11,29.85,87.64,29.85,58.50,42.00,25.56,0
3,3.62,3.04,4.17,4.04,3.56,4.98,2.40,88.10,88.12,1,...,91.98,27.10,68.75,31.60,64.25,31.47,72.30,43.24,28.38,0
4,4.08,2.68,4.73,3.20,3.11,5.39,3.46,87.01,87.03,1,...,92.11,26.76,68.74,32.30,64.23,32.17,72.53,44.00,28.04,0

In [3]:
df.tail()

,L_T1,L_T2,L_T3,L_T4,L_T5,L_T6,L_T7,F_PU1,F_PU2,S_PU2,...,P_J256,P_J289,P_J415,P_J302,P_J306,P_J307,P_J317,P_J14,P_J422,ATT_FLAG
4172,2.65,2.37,3.85,3.04,3.82,4.94,2.19,120.08,0.0,0,...,70.03,27.38,84.14,18.45,81.67,18.34,66.04,29.88,28.98,0
4173,2.24,2.56,3.42,2.92,3.69,5.02,1.97,119.12,0.0,0,...,68.60,27.66,83.46,25.40,60.85,25.28,66.89,30.19,29.29,0
4174,1.91,2.76,2.95,2.49,2.70,5.14,1.87,120.71,0.0,0,...,85.63,26.84,82.82,24.46,59.56,24.34,66.08,29.68,28.78,0
4175,1.52,2.52,3.33,2.03,1.69,5.10,1.39,120.02,0.0,0,...,86.15,25.78,103.63,24.77,59.01,24.65,66.42,28.98,28.08,0
4176,1.10,2.12,3.73,2.73,1.58,5.13,1.19,120.33,0.0,0,...,89.08,25.64,105.91,18.16,80.65,18.06,67.32,28.75,27.85,0

In [4]:
df.shape

(4177, 37)

In [5]:
df.size

154549

In [6]:
df.columns

Index(['L_T1', 'L_T2', 'L_T3', 'L_T4', 'L_T5', 'L_T6', 'L_T7', 'F_PU1',
       'F_PU2', 'S_PU2', 'F_PU4', 'S_PU4', 'F_PU6', 'S_PU6', 'F_PU7', 'S_PU7',
       'F_PU8', 'S_PU8', 'F_PU10', 'S_PU10', 'F_PU11', 'S_PU11', 'F_V2',
       'S_V2', 'P_J280', 'P_J269', 'P_J300', 'P_J256', 'P_J289', 'P_J415',
       'P_J302', 'P_J306', 'P_J307', 'P_J317', 'P_J14', 'P_J422', 'ATT_FLAG'],
      dtype='object')

In [7]:
df.isnull()

,L_T1,L_T2,L_T3,L_T4,L_T5,L_T6,L_T7,F_PU1,F_PU2,S_PU2,...,P_J256,P_J289,P_J415,P_J302,P_J306,P_J307,P_J317,P_J14,P_J422,ATT_FLAG
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4172,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4173,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4174,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4175,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4176,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [8]:
df = df.dropna()

In [9]:
df['ATT_FLAG'].unique()

array([0, 1], dtype=int64)

In [10]:
df.describe()

,L_T1,L_T2,L_T3,L_T4,L_T5,L_T6,L_T7,F_PU1,F_PU2,S_PU2,...,P_J256,P_J289,P_J415,P_J302,P_J306,P_J307,P_J317,P_J14,P_J422,ATT_FLAG
count,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,...,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000
mean,2.707446,3.287965,4.204496,3.556232,2.748377,5.368429,3.323352,100.839069,69.385904,0.730907,...,79.404214,27.772894,82.665293,24.574898,74.463383,24.482049,68.024829,33.906174,29.447544,0.117788
std,1.209627,1.470462,0.681352,0.544905,0.735800,0.177560,0.838134,10.217831,42.180931,0.443541,...,8.475271,2.740362,7.577549,4.712136,10.020099,4.734871,5.631171,4.599987,2.679226,0.322395
min,0.320000,0.310000,2.880000,1.920000,1.280000,4.770000,0.430000,38.920000,0.000000,0.000000,...,66.060000,19.460000,53.940000,13.910000,58.070000,13.640000,51.410000,27.820000,21.320000,0.000000
25%,1.650000,2.150000,3.620000,3.130000,2.130000,5.240000,2.660000,94.170000,0.000000,0.000000,...,71.960000,26.670000,83.860000,20.510000,62.930000,20.400000,66.680000,30.690000,28.430000,0.000000
50%,2.820000,3.490000,4.230000,3.550000,2.750000,5.500000,3.280000,96.650000,93.860000,1.000000,...,75.810000,28.140000,85.190000,23.160000,81.170000,23.050000,68.890000,32.250000,29.830000,0.000000
75%,3.780000,4.580000,4.800000,4.000000,3.370000,5.500000,4.040000,112.140000,96.510000,1.000000,...,88.170000,29.570000,86.380000,28.580000,82.650000,28.490000,71.360000,38.230000,31.290000,0.000000
max,5.730000,5.670000,5.430000,4.700000,4.160000,5.500000,5.000000,122.570000,99.920000,1.000000,...,94.870000,34.260000,107.950000,71.110000,95.270000,71.110000,93.730000,77.410000,35.680000,1.000000

In [11]:
df.corr()

,L_T1,L_T2,L_T3,L_T4,L_T5,L_T6,L_T7,F_PU1,F_PU2,S_PU2,...,P_J256,P_J289,P_J415,P_J302,P_J306,P_J307,P_J317,P_J14,P_J422,ATT_FLAG
L_T1,1.000000,-0.250684,-0.046836,0.008463,-0.106485,-0.053738,0.055432,0.007194,-0.233661,-0.204146,...,-0.080565,-0.340031,-0.012135,0.253651,0.009283,0.251984,-0.013322,0.398732,-0.358328,0.036239
L_T2,-0.250684,1.000000,-0.231006,0.066508,-0.099861,-0.163370,0.000885,-0.392417,0.410211,0.409832,...,-0.237924,0.595941,-0.079463,0.030834,0.006492,0.031052,-0.071780,0.230911,0.581199,0.013174
L_T3,-0.046836,-0.231006,1.000000,0.197330,0.054912,-0.079414,0.245431,-0.078215,0.072222,0.073211,...,0.060588,0.220987,-0.121430,0.362259,-0.308935,0.363193,0.000802,-0.216582,0.226282,0.000118
L_T4,0.008463,0.066508,0.197330,1.000000,-0.033190,-0.081583,0.132570,-0.065142,0.054495,0.054399,...,-0.104233,0.220389,-0.118869,0.130808,-0.069821,0.131393,-0.032399,-0.013947,0.211086,-0.060476
L_T5,-0.106485,-0.099861,0.054912,-0.033190,1.000000,0.107738,-0.017983,-0.036421,0.046216,0.044608,...,0.275713,-0.122484,0.010717,0.020127,0.010523,0.019797,0.083979,-0.025971,-0.110871,-0.004625
L_T6,-0.053738,-0.163370,-0.079414,-0.081583,0.107738,1.000000,0.489866,0.048450,-0.002425,-0.010020,...,0.225643,-0.224329,0.120181,-0.191834,0.058172,-0.193474,0.433380,-0.086280,-0.208184,-0.012371
L_T7,0.055432,0.000885,0.245431,0.132570,-0.017983,0.489866,1.000000,-0.078452,0.041655,0.046745,...,-0.050572,0.091534,-0.048361,0.249226,-0.127420,0.250525,0.068272,0.029983,0.086516,-0.012601
F_PU1,0.007194,-0.392417,-0.078215,-0.065142,-0.036421,0.048450,-0.078452,1.000000,-0.939660,-0.956029,...,-0.026326,-0.190982,0.063226,-0.311753,0.062938,-0.311078,-0.004065,-0.393910,-0.185570,-0.031497
F_PU2,-0.233661,0.410211,0.072222,0.054495,0.046216,-0.002425,0.041655,-0.939660,1.000000,0.998221,...,0.050392,0.309346,-0.016983,0.127646,-0.012337,0.127388,0.037909,0.125622,0.319158,0.011319
S_PU2,-0.204146,0.409832,0.073211,0.054399,0.044608,-0.010020,0.046745,-0.956029,0.998221,1.000000,...,0.043294,0.295427,-0.024304,0.155464,-0.019108,0.155145,0.032318,0.167831,0.302887,0.015731
F_PU4,-0.036709,-0.241508,-0.157865,-0.170804,0.255347,0.267064,-0.114335,0.031820,-0.005184,-0.012671,...,0.956489,-0.539861,0.150392,-0.158965,0.115358,-0.160064,0.185495,-0.042084,-0.492544,0.004295
S_PU4,-0.023748,-0.262219,-0.143805,-0.170518,0.257265,0.269462,-0.108913,0.030562,-0.010463,-0.017128,...,0.959329,-0.562754,0.153197,-0.148420,0.113258,-0.149544,0.189143,-0.027612,-0.516518,0.002724
F_PU6,-0.009382,-0.046604,-0.036560,-0.083712,-0.015742,0.058609,0.021642,0.052263,-0.046967,-0.047610,...,-0.009439,-0.065584,0.093233,-0.043644,0.013082,-0.043751,0.027173,-0.021653,-0.062462,0.374339
S_PU6,-0.008008,-0.051848,-0.037036,-0.090959,-0.018249,0.058984,0.014760,0.055620,-0.050828,-0.051367,...,-0.005865,-0.072471,0.103899,-0.043934,0.012338,-0.044049,0.027344,-0.021791,-0.068934,0.367945
F_PU7,0.021393,-0.077226,-0.239387,-0.180225,0.002316,0.139456,-0.099693,0.091968,-0.044043,-0.051849,...,0.100799,-0.426642,0.869105,-0.214785,0.121477,-0.215737,0.088458,-0.105857,-0.390990,-0.125574
S_PU7,0.036479,-0.107037,-0.227457,-0.188346,0.010501,0.146161,-0.102909,0.093715,-0.053660,-0.060468,...,0.125107,-0.464924,0.879793,-0.205426,0.120283,-0.206431,0.095926,-0.089484,-0.429501,-0.086880
F_PU8,0.012073,0.009063,-0.371080,-0.088542,-0.062370,0.071716,-0.151589,0.099290,-0.039088,-0.047245,...,0.008581,-0.168878,0.090584,-0.757631,0.990150,-0.754967,-0.044758,-0.002885,-0.168579,0.006496
S_PU8,-0.004241,0.005271,-0.369397,-0.090837,-0.051421,0.079044,-0.157817,0.109676,-0.042989,-0.052083,...,0.016102,-0.165988,0.093577,-0.778601,0.988371,-0.776018,-0.026527,-0.023040,-0.164699,0.002674
F_PU10,0.028063,-0.053908,-0.288713,-0.126033,0.025674,0.291230,-0.242169,0.097251,-0.043170,-0.051241,...,0.099623,-0.243045,0.132142,-0.497752,0.094086,-0.504735,0.806912,-0.013563,-0.236091,-0.024995
S_PU10,0.003357,-0.057858,-0.285741,-0.125629,0.027781,0.315649,-0.225523,0.110539,-0.045946,-0.055594,...,0.111081,-0.237752,0.138268,-0.547916,0.137399,-0.554714,0.827931,-0.043833,-0.229353,-0.019133
F_PU11,-0.001822,0.018009,-0.006295,-0.012105,-0.017020,-0.000023,-0.037695,0.015463,-0.006174,-0.008203,...,0.017862,0.000149,0.016830,-0.105047,-0.005911,-0.107731,0.249105,-0.018155,0.002118,0.232579
S_PU11,-0.003946,0.017994,-0.007472,-0.012394,-0.016937,0.001241,-0.039210,0.016348,-0.006469,-0.008600,...,0.018681,0.000238,0.018149,-0.107507,-0.003420,-0.110157,0.250386,-0.019245,0.002315,0.231946
F_V2,-0.312910,-0.176031,0.367224,0.084874,0.023962,0.026694,0.047887,0.135836,0.091317,0.058453,...,0.075485,0.484798,0.091750,-0.095100,-0.128041,-0.093407,-0.017694,-0.889420,0.541344,0.019641
S_V2,-0.457340,-0.031687,0.297465,0.092934,0.004979,0.002778,0.022006,0.202746,0.048946,0.013284,...,0.000028,0.596838,-0.010129,-0.178535,-0.092714,-0.176549,-0.031082,-0.886628,0.644614,0.003993
P_J280,0.445203,-0.343639,0.017924,-0.003835,-0.069695,-0.077880,0.035493,0.695541,-0.835552,-0.816534,...,-0.120199,-0.263739,-0.054646,0.084149,-0.063464,0.084226,-0.076677,0.063829,-0.283833,-0.002419
P_J269,-0.009816,0.394028,0.078926,0.066051,0.036576,-0.047801,0.078311,-0.999836,0.942804,0.958359,...,0.027799,0.193450,-0.062712,0.308148,-0.062739,0.307484,0.004936,0.388047,0.188328,0.030041
P_J300,-0.336591,0.595257,0.221024,0.220685,-0.126312,-0.226729,0.092470,-0.189531,0.306723,0.293013,...,-0.439252,0.999858,-0.380436,0.092368,-0.154122,0.094234,-0.148340,-0.331789,0.995843,0.014694
P_J256,-0.080565,-0.237924,0.060588,-0.104233,0.275713,0.225643,-0.050572,-0.026326,0.050392,0.043294,...,1.000000,-0.425149,0.102625,-0.049200,0.038701,-0.049852,0.182859,-0.090713,-0.376485,0.000514
P_J289,-0.340031,0.595941,0.220987,0.220389,-0.122484,-0.224329,0.091534,-0.190982,0.309346,0.295427,...,-0.425149,1.000000,-0.385609,0.091292,-0.153851,0.093157,-0.146494,-0.334583,0.996646,0.014817
P_J415,-0.012135,-0.079463,-0.121430,-0.118869,0.010717,0.120181,-0.048361,0.063226,-0.016983,-0.024304,...,0.102625,-0.385609,1.000000,-0.148580,0.075694,-0.149133,0.086293,-0.149136,-0.344946,0.003013
P_J302,0.253651,0.030834,0.362259,0.130808,0.020127,-0.191834,0.249226,-0.311753,0.127646,0.155464,...,-0.049200,0.091292,-0.148580,1.000000,-0.710470,0.999959,-0.300346,0.393911,0.074972,0.063321
P_J306,0.009283,0.006492,-0.308935,-0.069821,0.010523,0.058172,-0.127420,0.062938,-0.012337,-0.019108,...,0.038701,-0.153851,0.075694,-0.710470,1.000000,-0.707513,-0.058890,0.011010,-0.153579,0.007363
P_J307,0.251984,0.031052,0.363193,0.131393,0.019797,-0.193474,0.250525,-0.311078,0.127388,0.155145,...,-0.049852,0.093157,-0.149133,0.999959,-0.707513,1.000000,-0.307618,0.391959,0.076856,0.062262
P_J317,-0.013322,-0.071780,0.000802,-0.032399,0.083979,0.433380,0.068272,-0.004065,0.037909,0.032318,...,0.182859,-0.146494,0.086293,-0.300346,-0.058890,-0.307618,1.000000,-0.027448,-0.137758,0.047144
P_J14,0.398732,0.230911,-0.216582,-0.013947,-0.025971,-0.086280,0.029983,-0.393910,0.125622,0.167831,...,-0.090713,-0.334583,-0.149136,0.393911,0.011010,0.391959,-0.027448,1.000000,-0.388584,0.062989
P_J422,-0.358328,0.581199,0.226282,0.211086,-0.110871,-0.208184,0.086516,-0.185570,0.319158,0.302887,...,-0.376485,0.996646,-0.344946,0.074972,-0.153579,0.076856,-0.137758,-0.388584,1.000000,0.017135
ATT_FLAG,0.036239,0.013174,0.000118,-0.060476,-0.004625,-0.012371,-0.012601,-0.031497,0.011319,0.015731,...,0.000514,0.014817,0.003013,0.063321,0.007363,0.062262,0.047144,0.062989,0.017135,1.000000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 37 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   L_T1      4177 non-null   float64
 1   L_T2      4177 non-null   float64
 2   L_T3      4177 non-null   float64
 3   L_T4      4177 non-null   float64
 4   L_T5      4177 non-null   float64
 5   L_T6      4177 non-null   float64
 6   L_T7      4177 non-null   float64
 7   F_PU1     4177 non-null   float64
 8   F_PU2     4177 non-null   float64
 9   S_PU2     4177 non-null   int64
 10  F_PU4     4177 non-null   float64
 11  S_PU4     4177 non-null   int64
 12  F_PU6     4177 non-null   float64
 13  S_PU6     4177 non-null   int64
 14  F_PU7     4177 non-null   float64
 15  S_PU7     4177 non-null   int64
 16  F_PU8     4177 non-null   float64
 17  S_PU8     4177 non-null   int64
 18  F_PU10    4177 non-null   float64
 19  S_PU10    4177 non-null   int64
 20  F_PU11    4177 non-null   float64
 21  S_PU11    4177 non-null   int64
 22  F_V2      4177 non-null   float64
 23  S_V2      4177 non-null   int64
 24  P_J280    4177 non-null   float64
 25  P_J269    4177 non-null   float64
 26  P_J300    4177 non-null   float64
 27  P_J256    4177 non-null   float64
 28  P_J289    4177 non-null   float64
 29  P_J415    4177 non-null   float64
 30  P_J302    4177 non-null   float64
 31  P_J306    4177 non-null   float64
 32  P_J307    4177 non-null   float64
 33  P_J317    4177 non-null   float64
 34  P_J14     4177 non-null   float64
 35  P_J422    4177 non-null   float64
 36  ATT_FLAG  4177 non-null   int64
dtypes: float64(28), int64(9)
memory usage: 1.2 MB

In [13]:
pd.crosstab(df["L_T1"], df["L_T2"])

L_T2,0.31,0.32,0.35,0.37,0.38,0.39,0.40,0.41,0.43,0.44,...,5.56,5.57,5.58,5.59,5.60,5.61,5.63,5.64,5.65,5.67
L_T1,,,,,,,,,,,,,,,,,,,,,
0.32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.35,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.39,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.43,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.44,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5.28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5.37,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5.50,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5.66,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5.73,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
df.groupby(["L_T3","L_T5"]).groups

{(2.88, 1.78): [454], (2.89, 2.14): [1246], (2.89, 2.41): [3502], (2.89, 3.62): [2278], (2.9, 1.83): [2494], (2.9, 2.29): [1605], (2.9, 2.35): [1836], (2.9, 3.52): [213], (2.91, 2.15): [2374], (2.91, 2.59): [1547], (2.91, 2.66): [3179], (2.91, 2.72): [3755], (2.91, 3.76): [790], (2.91, 3.86): [2086], (2.92, 1.74): [1174], (2.92, 3.39): [742], (2.92, 3.55): [2758], (2.93, 1.93): [2411], (2.93, 2.85): [3875], (2.93, 2.88): [598], (2.94, 1.96): [814], (2.94, 3.35): [2075], (2.94, 3.64): [525], (2.95, 2.7): [4174], (2.95, 2.89): [2326], (2.95, 2.98): [2854], (2.95, 3.02): [4006], (2.95, 3.07): [2901], (2.95, 3.09): [418], (2.95, 3.53): [3947], (2.95, 3.95): [1365], (2.96, 2.11): [3909], (2.96, 2.43): [4139], (2.96, 2.52): [3370], (2.96, 3.07): [1990], (2.96, 3.13): [2579], (2.96, 3.38): [635], (2.96, 3.97): [130], (2.97, 2.58): [2638], (2.97, 3.14): [3069], (2.98, 1.58): [1043], (2.98, 2.7): [3766], (2.98, 3.85): [1883], (2.99, 2.14): [1534], (2.99, 3.53): [1283], (2.99, 3.77): [1031], (3.0, 2.92): [478], (3.0, 2.98): [1403], (3.0, 3.9): [4163], (3.0, 4.05): [1427], (3.01, 1.77): [2302], (3.01, 2.02): [2771], (3.01, 2.31): [611], (3.01, 2.42): [2733], (3.01, 2.47): [2435], (3.01, 2.63): [3971], (3.01, 2.66): [1067], (3.01, 2.69): [3995], (3.01, 2.8): [334], (3.01, 2.9): [1007], (3.01, 3.02): [3814], (3.01, 3.18): [429], (3.01, 3.27): [1331], (3.01, 3.66): [957], (3.01, 3.83): [2398], (3.02, 2.11): [3419], (3.02, 2.12): [1786], (3.02, 2.23): [2171], (3.02, 2.24): [2110], (3.02, 2.34): [93], (3.02, 2.78): [838], (3.03, 1.65): [3154], (3.03, 1.69): [2938], (3.03, 1.99): [2555], (3.03, 2.07): [3082], (3.03, 2.08): [237], (3.03, 2.19): [1738], (3.03, 2.31): [2253], (3.03, 2.36): [1811], (3.03, 2.38): [3742], (3.03, 2.62): [2890], (3.03, 2.69): [2194], (3.03, 2.78): [2133], (3.03, 2.91): [1414], (3.03, 3.01): [3203], (3.03, 3.1): [491], (3.03, 3.13): [1691], (3.03, 3.34): [851], (3.03, 3.61): [671], (3.03, 3.62): [1149], (3.03, 3.88): [1020], (3.04, 1.54): [226], (3.04, 1.65): [1054], (3.04, 1.77): [1163], (3.04, 2.0): [694], (3.04, 2.12): [3011], (3.04, 2.5): [707], (3.04, 2.71): [2661], (3.04, 2.75): [4067], (3.04, 2.94): [1222], ...}

In [15]:
df["ATT_FLAG"].value_counts()

ATT_FLAG
0    3685
1     492
Name: count, dtype: int64

In [17]:
pd.Categorical(df["S_PU2"]).describe()

            counts     freqs
categories
0             1124  0.269093
1             3053  0.730907

In [18]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4172    False
4173    False
4174    False
4175    False
4176    False
Length: 4177, dtype: bool

In [19]:
sum(df.duplicated())

0