# Model Building

In [1]:
# Import the neccessary packages
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy

C:\Users\SPIRO25\AppData\Local\Temp\ipykernel_6900\274915067.py:3: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
# Ignore the unnecssary warnings ( like software update, bugs, and so on so fourth)
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Set the display max columns datasets
pd.set_option('display.max_columns',None)

In [4]:
# Read the dataset
data = pd.read_csv('A.csv')

In [5]:
# Check the top values
data.head()

,DATETIME,L_T1,L_T2,L_T3,L_T4,L_T5,L_T6,L_T7,F_PU1,S_PU1,F_PU2,S_PU2,F_PU3,S_PU3,F_PU4,S_PU4,F_PU5,S_PU5,F_PU6,S_PU6,F_PU7,S_PU7,F_PU8,S_PU8,F_PU9,S_PU9,F_PU10,S_PU10,F_PU11,S_PU11,F_V2,S_V2,P_J280,P_J269,P_J300,P_J256,P_J289,P_J415,P_J302,P_J306,P_J307,P_J317,P_J14,P_J422,ATT_FLAG
0,04/07/16 00,2.44,5.24,3.19,4.10,2.86,5.50,4.39,93.63,1,93.65,1,0,0,0.00,0,0,0,0.0,0,49.84,1,35.54,1,0,0,29.87,1,0.0,0,0.0,0,2.98,36.38,28.26,70.00,28.22,85.87,21.69,82.72,21.58,71.99,39.33,29.64,0
1,04/07/16 01,2.66,4.53,3.20,4.18,3.29,5.44,4.53,89.41,1,89.43,1,0,0,34.26,1,0,0,0.0,0,48.38,1,37.83,1,0,0,0.00,0,0.0,0,0.0,0,2.98,38.60,24.39,87.73,24.45,84.87,29.81,86.62,29.81,59.76,42.17,26.15,0
2,04/07/16 02,3.11,3.66,3.66,4.21,3.87,5.15,3.22,89.88,1,89.89,1,0,0,32.97,1,0,0,0.0,0,46.84,1,37.31,1,0,0,0.00,0,0.0,0,0.0,0,2.98,38.36,23.84,89.29,23.90,87.11,29.85,87.64,29.85,58.50,42.00,25.56,0
3,04/07/16 03,3.62,3.04,4.17,4.04,3.56,4.98,2.40,88.10,1,88.12,1,0,0,33.27,1,0,0,0.0,0,0.00,0,0.00,0,0,0,32.68,1,0.0,0,0.0,0,2.98,39.29,27.00,91.98,27.10,68.75,31.60,64.25,31.47,72.30,43.24,28.38,0
4,04/07/16 04,4.08,2.68,4.73,3.20,3.11,5.39,3.46,87.01,1,87.03,1,0,0,32.99,1,0,0,0.0,0,0.00,0,0.00,0,0,0,32.81,1,0.0,0,0.0,0,2.98,39.85,26.67,92.11,26.76,68.74,32.30,64.23,32.17,72.53,44.00,28.04,0

In [7]:
del data['DATETIME']
del data['F_PU9']
del data['S_PU9']
del data['F_PU5']
del data['S_PU5']
del data['F_PU3']
del data['S_PU3']
del data['S_PU1']

In [8]:
# Remove the null values
df1 = data.dropna()

In [9]:
df1.head()

,L_T1,L_T2,L_T3,L_T4,L_T5,L_T6,L_T7,F_PU1,F_PU2,S_PU2,F_PU4,S_PU4,F_PU6,S_PU6,F_PU7,S_PU7,F_PU8,S_PU8,F_PU10,S_PU10,F_PU11,S_PU11,F_V2,S_V2,P_J280,P_J269,P_J300,P_J256,P_J289,P_J415,P_J302,P_J306,P_J307,P_J317,P_J14,P_J422,ATT_FLAG
0,2.44,5.24,3.19,4.10,2.86,5.50,4.39,93.63,93.65,1,0.00,0,0.0,0,49.84,1,35.54,1,29.87,1,0.0,0,0.0,0,2.98,36.38,28.26,70.00,28.22,85.87,21.69,82.72,21.58,71.99,39.33,29.64,0
1,2.66,4.53,3.20,4.18,3.29,5.44,4.53,89.41,89.43,1,34.26,1,0.0,0,48.38,1,37.83,1,0.00,0,0.0,0,0.0,0,2.98,38.60,24.39,87.73,24.45,84.87,29.81,86.62,29.81,59.76,42.17,26.15,0
2,3.11,3.66,3.66,4.21,3.87,5.15,3.22,89.88,89.89,1,32.97,1,0.0,0,46.84,1,37.31,1,0.00,0,0.0,0,0.0,0,2.98,38.36,23.84,89.29,23.90,87.11,29.85,87.64,29.85,58.50,42.00,25.56,0
3,3.62,3.04,4.17,4.04,3.56,4.98,2.40,88.10,88.12,1,33.27,1,0.0,0,0.00,0,0.00,0,32.68,1,0.0,0,0.0,0,2.98,39.29,27.00,91.98,27.10,68.75,31.60,64.25,31.47,72.30,43.24,28.38,0
4,4.08,2.68,4.73,3.20,3.11,5.39,3.46,87.01,87.03,1,32.99,1,0.0,0,0.00,0,0.00,0,32.81,1,0.0,0,0.0,0,2.98,39.85,26.67,92.11,26.76,68.74,32.30,64.23,32.17,72.53,44.00,28.04,0

In [10]:
df = df1.rename({'Stress Level':'Stress_level'},axis=1)

In [11]:
# Check the total number of null values.
df.isnull().sum()

L_T1        0
L_T2        0
L_T3        0
L_T4        0
L_T5        0
L_T6        0
L_T7        0
F_PU1       0
F_PU2       0
S_PU2       0
F_PU4       0
S_PU4       0
F_PU6       0
S_PU6       0
F_PU7       0
S_PU7       0
F_PU8       0
S_PU8       0
F_PU10      0
S_PU10      0
F_PU11      0
S_PU11      0
F_V2        0
S_V2        0
P_J280      0
P_J269      0
P_J300      0
P_J256      0
P_J289      0
P_J415      0
P_J302      0
P_J306      0
P_J307      0
P_J317      0
P_J14       0
P_J422      0
ATT_FLAG    0
dtype: int64

In [12]:
df.head(20)

,L_T1,L_T2,L_T3,L_T4,L_T5,L_T6,L_T7,F_PU1,F_PU2,S_PU2,F_PU4,S_PU4,F_PU6,S_PU6,F_PU7,S_PU7,F_PU8,S_PU8,F_PU10,S_PU10,F_PU11,S_PU11,F_V2,S_V2,P_J280,P_J269,P_J300,P_J256,P_J289,P_J415,P_J302,P_J306,P_J307,P_J317,P_J14,P_J422,ATT_FLAG
0,2.44,5.24,3.19,4.10,2.86,5.50,4.39,93.63,93.65,1,0.00,0,0.0,0,49.84,1,35.54,1,29.87,1,0.0,0,0.00,0,2.98,36.38,28.26,70.00,28.22,85.87,21.69,82.72,21.58,71.99,39.33,29.64,0
1,2.66,4.53,3.20,4.18,3.29,5.44,4.53,89.41,89.43,1,34.26,1,0.0,0,48.38,1,37.83,1,0.00,0,0.0,0,0.00,0,2.98,38.60,24.39,87.73,24.45,84.87,29.81,86.62,29.81,59.76,42.17,26.15,0
2,3.11,3.66,3.66,4.21,3.87,5.15,3.22,89.88,89.89,1,32.97,1,0.0,0,46.84,1,37.31,1,0.00,0,0.0,0,0.00,0,2.98,38.36,23.84,89.29,23.90,87.11,29.85,87.64,29.85,58.50,42.00,25.56,0
3,3.62,3.04,4.17,4.04,3.56,4.98,2.40,88.10,88.12,1,33.27,1,0.0,0,0.00,0,0.00,0,32.68,1,0.0,0,0.00,0,2.98,39.29,27.00,91.98,27.10,68.75,31.60,64.25,31.47,72.30,43.24,28.38,0
4,4.08,2.68,4.73,3.20,3.11,5.39,3.46,87.01,87.03,1,32.99,1,0.0,0,0.00,0,0.00,0,32.81,1,0.0,0,0.00,0,2.98,39.85,26.67,92.11,26.76,68.74,32.30,64.23,32.17,72.53,44.00,28.04,0
5,4.53,2.10,5.26,3.29,2.76,5.50,4.67,110.09,0.00,0,30.43,1,0.0,0,46.60,1,0.00,0,30.26,1,0.0,0,0.00,0,2.99,27.41,22.59,91.94,22.64,86.26,30.41,63.36,30.30,79.47,39.76,24.28,0
6,4.84,1.57,5.12,3.90,2.29,5.30,3.90,107.71,0.00,0,0.00,0,0.0,0,47.35,1,0.00,0,0.00,0,0.0,0,0.00,0,2.99,28.74,24.78,75.29,24.74,87.03,33.98,63.13,33.98,59.47,41.24,26.13,0
7,5.19,1.07,4.85,4.45,1.87,5.00,2.66,110.23,0.00,0,0.00,0,0.0,0,47.66,1,0.00,0,0.00,0,0.0,0,0.00,0,2.99,27.33,24.25,73.65,24.22,85.95,33.22,61.75,33.22,55.73,40.05,25.61,0
8,5.22,0.94,4.52,3.51,1.55,5.09,2.48,111.38,0.00,0,0.00,0,0.0,0,0.00,0,37.03,1,31.53,1,0.0,0,0.00,0,2.99,26.68,25.94,71.43,25.94,57.78,22.73,81.09,22.61,67.51,39.26,27.13,0
9,5.11,0.68,4.11,2.41,1.77,5.27,2.57,112.78,0.00,0,0.00,0,0.0,0,48.44,1,36.30,1,31.38,1,0.0,0,0.00,0,2.99,25.89,23.81,67.55,23.77,84.09,22.21,81.90,22.10,67.53,38.59,25.17,0
10,4.73,0.62,3.59,2.66,2.13,5.43,2.63,117.50,0.00,0,0.00,0,0.0,0,50.13,1,35.33,1,30.91,1,0.0,0,88.73,1,2.99,23.19,26.55,71.49,26.51,83.59,19.96,81.37,19.85,66.85,29.13,28.23,0
11,4.24,1.01,3.22,2.52,2.50,5.50,2.53,118.65,0.00,0,0.00,0,0.0,0,49.76,1,34.44,1,30.27,1,0.0,0,82.43,1,2.99,22.53,26.65,71.99,26.61,84.42,19.57,82.51,19.47,68.58,29.19,28.29,0
12,3.74,1.23,3.17,2.67,3.03,5.50,2.70,118.91,0.00,0,34.87,1,0.0,0,48.57,1,34.77,1,30.14,1,0.0,0,85.34,1,2.99,22.38,25.65,87.98,25.72,85.79,19.32,81.68,19.21,68.76,28.61,27.71,0
13,3.25,1.25,3.64,3.13,3.38,5.50,2.89,121.45,0.00,0,35.25,1,0.0,0,48.61,1,33.86,1,29.95,1,0.0,0,73.53,1,2.99,20.90,25.56,87.23,25.63,85.62,17.95,81.85,17.84,68.01,28.46,27.56,0
14,2.70,1.13,4.07,3.49,3.80,5.50,2.90,119.84,0.00,0,34.71,1,0.0,0,48.82,1,34.47,1,30.10,1,0.0,0,80.99,1,2.99,21.84,25.54,88.13,25.60,85.21,18.72,81.59,18.61,68.29,28.47,27.57,0
15,2.25,1.09,4.51,3.69,4.07,5.50,2.95,118.63,0.00,0,33.58,1,0.0,0,49.16,1,0.00,0,30.88,1,0.0,0,87.53,1,2.99,22.54,25.55,90.03,25.61,84.57,25.87,63.44,25.76,72.86,28.51,27.61,0
16,1.93,1.14,5.01,3.67,3.37,5.50,3.70,118.64,0.00,0,34.31,1,0.0,0,48.76,1,0.00,0,31.36,1,0.0,0,86.82,1,2.99,22.53,25.58,88.84,25.64,85.35,25.73,62.83,25.61,71.10,28.54,27.64,0
17,1.65,1.27,5.17,3.88,2.70,5.50,4.02,118.09,0.00,0,0.00,0,0.0,0,49.08,1,0.00,0,31.29,1,0.0,0,81.56,1,2.99,22.85,26.90,73.53,26.87,85.98,25.99,62.44,25.87,71.60,29.44,28.54,0
18,1.43,1.61,4.82,4.13,2.06,5.50,4.38,119.24,0.00,0,0.00,0,0.0,0,49.42,1,0.00,0,30.78,1,0.0,0,75.59,1,2.99,22.19,26.97,72.12,26.93,85.40,25.42,61.04,25.31,72.77,29.47,28.57,0
19,1.15,1.87,4.43,4.18,1.61,5.43,4.46,120.18,0.00,0,0.00,0,0.0,0,49.26,1,36.72,1,0.00,0,0.0,0,69.84,1,2.99,21.64,27.03,71.12,26.99,85.76,24.04,82.90,24.04,57.40,29.50,28.60,0

In [13]:
# Check the data relationships
# df.head(20)

In [14]:
# Check the unique values in specific columns
df['ATT_FLAG'].unique()

array([0, 1], dtype=int64)

In [15]:
# Split the datasets into traing process X is (independent features, independent features)
x1 = df.drop(labels='ATT_FLAG',axis=1)
y1 = df.loc[:,'ATT_FLAG']

In [16]:
x1.head(20)

,L_T1,L_T2,L_T3,L_T4,L_T5,L_T6,L_T7,F_PU1,F_PU2,S_PU2,F_PU4,S_PU4,F_PU6,S_PU6,F_PU7,S_PU7,F_PU8,S_PU8,F_PU10,S_PU10,F_PU11,S_PU11,F_V2,S_V2,P_J280,P_J269,P_J300,P_J256,P_J289,P_J415,P_J302,P_J306,P_J307,P_J317,P_J14,P_J422
0,2.44,5.24,3.19,4.10,2.86,5.50,4.39,93.63,93.65,1,0.00,0,0.0,0,49.84,1,35.54,1,29.87,1,0.0,0,0.00,0,2.98,36.38,28.26,70.00,28.22,85.87,21.69,82.72,21.58,71.99,39.33,29.64
1,2.66,4.53,3.20,4.18,3.29,5.44,4.53,89.41,89.43,1,34.26,1,0.0,0,48.38,1,37.83,1,0.00,0,0.0,0,0.00,0,2.98,38.60,24.39,87.73,24.45,84.87,29.81,86.62,29.81,59.76,42.17,26.15
2,3.11,3.66,3.66,4.21,3.87,5.15,3.22,89.88,89.89,1,32.97,1,0.0,0,46.84,1,37.31,1,0.00,0,0.0,0,0.00,0,2.98,38.36,23.84,89.29,23.90,87.11,29.85,87.64,29.85,58.50,42.00,25.56
3,3.62,3.04,4.17,4.04,3.56,4.98,2.40,88.10,88.12,1,33.27,1,0.0,0,0.00,0,0.00,0,32.68,1,0.0,0,0.00,0,2.98,39.29,27.00,91.98,27.10,68.75,31.60,64.25,31.47,72.30,43.24,28.38
4,4.08,2.68,4.73,3.20,3.11,5.39,3.46,87.01,87.03,1,32.99,1,0.0,0,0.00,0,0.00,0,32.81,1,0.0,0,0.00,0,2.98,39.85,26.67,92.11,26.76,68.74,32.30,64.23,32.17,72.53,44.00,28.04
5,4.53,2.10,5.26,3.29,2.76,5.50,4.67,110.09,0.00,0,30.43,1,0.0,0,46.60,1,0.00,0,30.26,1,0.0,0,0.00,0,2.99,27.41,22.59,91.94,22.64,86.26,30.41,63.36,30.30,79.47,39.76,24.28
6,4.84,1.57,5.12,3.90,2.29,5.30,3.90,107.71,0.00,0,0.00,0,0.0,0,47.35,1,0.00,0,0.00,0,0.0,0,0.00,0,2.99,28.74,24.78,75.29,24.74,87.03,33.98,63.13,33.98,59.47,41.24,26.13
7,5.19,1.07,4.85,4.45,1.87,5.00,2.66,110.23,0.00,0,0.00,0,0.0,0,47.66,1,0.00,0,0.00,0,0.0,0,0.00,0,2.99,27.33,24.25,73.65,24.22,85.95,33.22,61.75,33.22,55.73,40.05,25.61
8,5.22,0.94,4.52,3.51,1.55,5.09,2.48,111.38,0.00,0,0.00,0,0.0,0,0.00,0,37.03,1,31.53,1,0.0,0,0.00,0,2.99,26.68,25.94,71.43,25.94,57.78,22.73,81.09,22.61,67.51,39.26,27.13
9,5.11,0.68,4.11,2.41,1.77,5.27,2.57,112.78,0.00,0,0.00,0,0.0,0,48.44,1,36.30,1,31.38,1,0.0,0,0.00,0,2.99,25.89,23.81,67.55,23.77,84.09,22.21,81.90,22.10,67.53,38.59,25.17
10,4.73,0.62,3.59,2.66,2.13,5.43,2.63,117.50,0.00,0,0.00,0,0.0,0,50.13,1,35.33,1,30.91,1,0.0,0,88.73,1,2.99,23.19,26.55,71.49,26.51,83.59,19.96,81.37,19.85,66.85,29.13,28.23
11,4.24,1.01,3.22,2.52,2.50,5.50,2.53,118.65,0.00,0,0.00,0,0.0,0,49.76,1,34.44,1,30.27,1,0.0,0,82.43,1,2.99,22.53,26.65,71.99,26.61,84.42,19.57,82.51,19.47,68.58,29.19,28.29
12,3.74,1.23,3.17,2.67,3.03,5.50,2.70,118.91,0.00,0,34.87,1,0.0,0,48.57,1,34.77,1,30.14,1,0.0,0,85.34,1,2.99,22.38,25.65,87.98,25.72,85.79,19.32,81.68,19.21,68.76,28.61,27.71
13,3.25,1.25,3.64,3.13,3.38,5.50,2.89,121.45,0.00,0,35.25,1,0.0,0,48.61,1,33.86,1,29.95,1,0.0,0,73.53,1,2.99,20.90,25.56,87.23,25.63,85.62,17.95,81.85,17.84,68.01,28.46,27.56
14,2.70,1.13,4.07,3.49,3.80,5.50,2.90,119.84,0.00,0,34.71,1,0.0,0,48.82,1,34.47,1,30.10,1,0.0,0,80.99,1,2.99,21.84,25.54,88.13,25.60,85.21,18.72,81.59,18.61,68.29,28.47,27.57
15,2.25,1.09,4.51,3.69,4.07,5.50,2.95,118.63,0.00,0,33.58,1,0.0,0,49.16,1,0.00,0,30.88,1,0.0,0,87.53,1,2.99,22.54,25.55,90.03,25.61,84.57,25.87,63.44,25.76,72.86,28.51,27.61
16,1.93,1.14,5.01,3.67,3.37,5.50,3.70,118.64,0.00,0,34.31,1,0.0,0,48.76,1,0.00,0,31.36,1,0.0,0,86.82,1,2.99,22.53,25.58,88.84,25.64,85.35,25.73,62.83,25.61,71.10,28.54,27.64
17,1.65,1.27,5.17,3.88,2.70,5.50,4.02,118.09,0.00,0,0.00,0,0.0,0,49.08,1,0.00,0,31.29,1,0.0,0,81.56,1,2.99,22.85,26.90,73.53,26.87,85.98,25.99,62.44,25.87,71.60,29.44,28.54
18,1.43,1.61,4.82,4.13,2.06,5.50,4.38,119.24,0.00,0,0.00,0,0.0,0,49.42,1,0.00,0,30.78,1,0.0,0,75.59,1,2.99,22.19,26.97,72.12,26.93,85.40,25.42,61.04,25.31,72.77,29.47,28.57
19,1.15,1.87,4.43,4.18,1.61,5.43,4.46,120.18,0.00,0,0.00,0,0.0,0,49.26,1,36.72,1,0.00,0,0.0,0,69.84,1,2.99,21.64,27.03,71.12,26.99,85.76,24.04,82.90,24.04,57.40,29.50,28.60

In [17]:
x1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 36 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   L_T1    4177 non-null   float64
 1   L_T2    4177 non-null   float64
 2   L_T3    4177 non-null   float64
 3   L_T4    4177 non-null   float64
 4   L_T5    4177 non-null   float64
 5   L_T6    4177 non-null   float64
 6   L_T7    4177 non-null   float64
 7   F_PU1   4177 non-null   float64
 8   F_PU2   4177 non-null   float64
 9   S_PU2   4177 non-null   int64
 10  F_PU4   4177 non-null   float64
 11  S_PU4   4177 non-null   int64
 12  F_PU6   4177 non-null   float64
 13  S_PU6   4177 non-null   int64
 14  F_PU7   4177 non-null   float64
 15  S_PU7   4177 non-null   int64
 16  F_PU8   4177 non-null   float64
 17  S_PU8   4177 non-null   int64
 18  F_PU10  4177 non-null   float64
 19  S_PU10  4177 non-null   int64
 20  F_PU11  4177 non-null   float64
 21  S_PU11  4177 non-null   int64
 22  F_V2    4177 non-null   float64
 23  S_V2    4177 non-null   int64
 24  P_J280  4177 non-null   float64
 25  P_J269  4177 non-null   float64
 26  P_J300  4177 non-null   float64
 27  P_J256  4177 non-null   float64
 28  P_J289  4177 non-null   float64
 29  P_J415  4177 non-null   float64
 30  P_J302  4177 non-null   float64
 31  P_J306  4177 non-null   float64
 32  P_J307  4177 non-null   float64
 33  P_J317  4177 non-null   float64
 34  P_J14   4177 non-null   float64
 35  P_J422  4177 non-null   float64
dtypes: float64(28), int64(8)
memory usage: 1.1 MB

In [18]:
# Balance the datasets
import imblearn
from imblearn.over_sampling import RandomOverSampler
from collections import Counter

ros =RandomOverSampler(random_state=1)
x,y=ros.fit_resample(x1,y1)
print("OUR DATASET COUNT         : ", Counter(y1))
print("OVER SAMPLING DATA COUNT  : ", Counter(y))

OUR DATASET COUNT         :  Counter({0: 3685, 1: 492})
OVER SAMPLING DATA COUNT  :  Counter({0: 3685, 1: 3685})

In [19]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7370 entries, 0 to 7369
Data columns (total 36 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   L_T1    7370 non-null   float64
 1   L_T2    7370 non-null   float64
 2   L_T3    7370 non-null   float64
 3   L_T4    7370 non-null   float64
 4   L_T5    7370 non-null   float64
 5   L_T6    7370 non-null   float64
 6   L_T7    7370 non-null   float64
 7   F_PU1   7370 non-null   float64
 8   F_PU2   7370 non-null   float64
 9   S_PU2   7370 non-null   int64
 10  F_PU4   7370 non-null   float64
 11  S_PU4   7370 non-null   int64
 12  F_PU6   7370 non-null   float64
 13  S_PU6   7370 non-null   int64
 14  F_PU7   7370 non-null   float64
 15  S_PU7   7370 non-null   int64
 16  F_PU8   7370 non-null   float64
 17  S_PU8   7370 non-null   int64
 18  F_PU10  7370 non-null   float64
 19  S_PU10  7370 non-null   int64
 20  F_PU11  7370 non-null   float64
 21  S_PU11  7370 non-null   int64
 22  F_V2    7370 non-null   float64
 23  S_V2    7370 non-null   int64
 24  P_J280  7370 non-null   float64
 25  P_J269  7370 non-null   float64
 26  P_J300  7370 non-null   float64
 27  P_J256  7370 non-null   float64
 28  P_J289  7370 non-null   float64
 29  P_J415  7370 non-null   float64
 30  P_J302  7370 non-null   float64
 31  P_J306  7370 non-null   float64
 32  P_J307  7370 non-null   float64
 33  P_J317  7370 non-null   float64
 34  P_J14   7370 non-null   float64
 35  P_J422  7370 non-null   float64
dtypes: float64(28), int64(8)
memory usage: 2.0 MB

In [20]:
# Split the datasets into training and testing
from sklearn.model_selection import train_test_split

x_train,x_test, y_train, y_test = train_test_split(x,y, test_size=0.50)

In [21]:
# Check the unique values
y.unique()

array([0, 1], dtype=int64)

In [22]:
# Import the model build algorithm
from sklearn.ensemble import RandomForestClassifier


clf = RandomForestClassifier()
clf.fit(x_train, y_train)
predictRFC =clf.predict(x_test)

In [23]:
# Check the accuracy score of this model
from sklearn.metrics import accuracy_score

accuracy_score = accuracy_score(y_test, predictRFC)* 100
print("Accuracy Score\n\n", accuracy_score)

Accuracy Score

 98.34464043419267

In [24]:
# Check the number True positive value, True negative value of this model
from sklearn.metrics import confusion_matrix

conf = confusion_matrix(y_test, predictRFC)
print("Confusion matrix\n\n", conf)

Confusion matrix

 [[1805   44]
 [  17 1819]]

In [25]:
# Check the classification report of this model
from sklearn.metrics import classification_report

report = classification_report(y_test, predictRFC)
print("Classification Report\n\n",report)

Classification Report

               precision    recall  f1-score   support

           0       0.99      0.98      0.98      1849
           1       0.98      0.99      0.98      1836

    accuracy                           0.98      3685
   macro avg       0.98      0.98      0.98      3685
weighted avg       0.98      0.98      0.98      3685

In [26]:
# Save the model for deployment purpose.
import joblib
joblib.dump(clf, 'RFE.pkl')

['RFE.pkl']